build: off

before_test: 
  - curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
  - 7z x stack.zip stack.exe
  - curl -ocabal.tar.gz https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-i386-unknown-mingw32.tar.gz
  - 7z x cabal.tar.gz
  - 7z x cabal.tar
  - ren cabal-1.22.0.0-i386-unknown-mingw32.exe cabal.exe
  - stack exec -- ghc --version


test_script:
  - stack init
  - stack setup > nul
  - echo "" | stack --no-terminal build
  - stack test
